version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Main application port
      - "9229:9229"  # Debug port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    depends_on:
      - test-runner

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test:watch
    depends_on:
      - performance-test

  # Performance testing service
  performance-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - PERFORMANCE_TEST=true
    command: npm run test:performance

  # Documentation service (for serving docs)
  docs:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html
    depends_on:
      - app

networks:
  default:
    name: space-invaders-network
    driver: bridge

volumes:
  node_modules: